<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FTIU28S" failures="12" tests="26" name="Explore_Products_Tab.VerifyAccountsOption" time="1200.137" errors="1" timestamp="2023-03-29T09:34:58 IST" skipped="0">
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyAllTheOptionsPresentInAccountsOption" time="9.191"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyAllTheOptionsPresentInAccountsOption" time="17.242"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSavingAccountOptionPresentInAccountsOption" time="45.388">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheSavingAccountOptionPresentInAccountsOption(VerifyAccountsOption.java:140)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyTheSavingAccountOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSavingAccountOptionPresentInAccountsOption" time="142.060"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSilverLiningsProgramOptionPresentInAccountsOption" time="20.495">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheSilverLiningsProgramOptionPresentInAccountsOption(VerifyAccountsOption.java:154)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyTheSilverLiningsProgramOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSilverLiningsProgramOptionPresentInAccountsOption" time="25.704"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSalaryAccountOptionPresentInAccountsOption" time="22.478">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheSalaryAccountOptionPresentInAccountsOption(VerifyAccountsOption.java:169)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyTheSalaryAccountOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSalaryAccountOptionPresentInAccountsOption" time="13.095"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheTrustNgoSavingsAccountOptionPresentInAccountsOption" time="19.909"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheTrustNgoSavingsAccountOptionPresentInAccountsOption" time="22.242">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheTrustNgoSavingsAccountOptionPresentInAccountsOption(VerifyAccountsOption.java:184)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyTheTrustNgoSavingsAccountOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyThePensionDisbursementAccountOptionPresentInAccountsOption" time="137.203"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyThePensionDisbursementAccountOptionPresentInAccountsOption" time="22.356">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyThePensionDisbursementAccountOptionPresentInAccountsOption(VerifyAccountsOption.java:281)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyThePensionDisbursementAccountOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyThePublicProvidentFundOptionPresentInAccountsOption" time="119.864"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyThePublicProvidentFundOptionPresentInAccountsOption" time="24.609">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyThePublicProvidentFundOptionPresentInAccountsOption(VerifyAccountsOption.java:216)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyThePublicProvidentFundOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyThePMJDYOptionPresentInAccountsOption" time="9.604">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyThePMJDYOptionPresentInAccountsOption(VerifyAccountsOption.java:313)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyThePMJDYOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyThePMJDYOptionPresentInAccountsOption" time="14.530"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSafeDepositLockerOptionPresentInAccountsOption" time="10.764">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheSafeDepositLockerOptionPresentInAccountsOption(VerifyAccountsOption.java:251)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyTheSafeDepositLockerOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSafeDepositLockerOptionPresentInAccountsOption" time="42.510"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSafeCustodyOptionPresentInAccountsOption" time="26.313">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/safe-custody] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/safe-custody] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheSafeCustodyOptionPresentInAccountsOption(VerifyAccountsOption.java:266)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyTheSafeCustodyOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheSafeCustodyOptionPresentInAccountsOption" time="24.988"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheCurrentAccountOptionPresentInAccountsOption" time="11.311">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/safe-custody] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/safe-custody] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheCurrentAccountOptionPresentInAccountsOption(VerifyAccountsOption.java:201)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyTheCurrentAccountOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheCurrentAccountOptionPresentInAccountsOption" time="19.349"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheAxisDirectInvestAccountOptionPresentInAccountsOption" time="18.416">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/safe-custody] but found [https://www.axisbank.com/],
	expected [https://digitalaccount.axisdirect.in/register] but found [about:blank]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/safe-custody] but found [https://www.axisbank.com/],
expected [https://digitalaccount.axisdirect.in/register] but found [about:blank]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheAxisDirectInvestAccountOptionPresentInAccountsOption(VerifyAccountsOption.java:236)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyTheAxisDirectInvestAccountOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheAxisDirectInvestAccountOptionPresentInAccountsOption" time="27.575"/>
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheAxisActiveOptionPresentInAccountsOption" time="13.046">
    <failure message="The following asserts failed:
	expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/],
	expected [https://www.axisbank.com/retail/accounts/safe-custody] but found [https://www.axisbank.com/],
	expected [https://digitalaccount.axisdirect.in/register] but found [about:blank],
	expected [https://www.axisbank.com/axisactive/index] but found [https://www.axisbank.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.axisbank.com/retail/accounts/savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/silver-linings-program?cta=homepage-main-menu-silver-linings-program] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/trust-ngo-institutional-savings-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/pension-disbursement-account] but found [https://www.axisbank.com/],
expected [https://www.axisbank.com/retail/accounts/safe-custody] but found [https://www.axisbank.com/],
expected [https://digitalaccount.axisdirect.in/register] but found [about:blank],
expected [https://www.axisbank.com/axisactive/index] but found [https://www.axisbank.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheAxisActiveOptionPresentInAccountsOption(VerifyAccountsOption.java:298)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyTheAxisActiveOptionPresentInAccountsOption -->
  <system-out/>
  <testcase classname="Explore_Products_Tab.VerifyAccountsOption" name="verifyTheAxisActiveOptionPresentInAccountsOption" time="339.895">
    <error message="timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=111.0.5563.111)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-FTIU28S&#039;, ip: &#039;192.168.184.1&#039;, os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.5&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 111.0.5563.111, chrome: {chromedriverVersion: 111.0.5563.64 (c710e93d5b63..., userDataDir: C:\Users\Akash\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:53578}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 81d507a5e3134843044eca275798903d" type="org.openqa.selenium.TimeoutException">
      <![CDATA[org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=111.0.5563.111)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-FTIU28S', ip: '192.168.184.1', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 111.0.5563.111, chrome: {chromedriverVersion: 111.0.5563.64 (c710e93d5b63..., userDataDir: C:\Users\Akash\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:53578}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 81d507a5e3134843044eca275798903d
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy17.click(Unknown Source)
at Explore_Products_Tab.AccountsOption.clickOnAxisActive(AccountsOption.java:105)
at Explore_Products_Tab.VerifyAccountsOption.verifyTheAxisActiveOptionPresentInAccountsOption(VerifyAccountsOption.java:290)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- verifyTheAxisActiveOptionPresentInAccountsOption -->
  <system-out/>
</testsuite> <!-- Explore_Products_Tab.VerifyAccountsOption -->
